name: Docker build and publish
on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      context:
        type: string
        required: false
        default: ./
      dockerfile:
        type: string
        required: false
        default: ./Dockerfile

      registry:
        type: string
        required: false
        default: ghcr.io # Use docker.io for Docker Hub if empty
      image_name:
        type: string
        required: true
      platforms:
        type: string
        required: false
        default: linux/amd64, linux/arm64

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.7.0
        with:
          cosign-release: 'v2.4.1'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ inputs.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ inputs.image_name }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ inputs.image_name }}:latest
            ${{ inputs.image_name }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
